spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates: Path=/api/students/**
          filters: StripPrefix=2
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090